export const TESTIMONIALS_CARDS = [
  {
    id: 1,
    href: "https://maps.app.goo.gl/fakeLink1",
    avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
    name: "Carlos Mendes",
    testimony: "Excelente atendimento, muito profissional.",
  },
  {
    id: 2,
    href: "https://maps.app.goo.gl/fakeLink2",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    name: "Fernanda Oliveira",
    testimony: "Me ajudaram muito durante todo o processo.",
  },
  {
    id: 3,
    href: "https://maps.app.goo.gl/fakeLink3",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    name: "Ricardo Alves",
    testimony: "Serviço impecável, recomendo sem dúvidas.",
  },
  {
    id: 4,
    href: "https://maps.app.goo.gl/fakeLink4",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    name: "Juliana Costa",
    testimony: "Muito atenciosos e rápidos na resolução.",
  },
  {
    id: 5,
    href: "https://maps.app.goo.gl/fakeLink5",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    name: "Marcos Vinicius",
    testimony: "Profissionais extremamente competentes.",
  },
  {
    id: 6,
    href: "https://maps.app.goo.gl/fakeLink6",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    name: "Camila Rocha",
    testimony: "Superou minhas expectativas.",
  },
  {
    id: 7,
    href: "https://maps.app.goo.gl/fakeLink7",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde",
    name: "Lucas Ribeiro",
    testimony: "Atendimento excelente do início ao fim.",
  },
  {
    id: 8,
    href: "https://maps.app.goo.gl/fakeLink8",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    name: "Patricia Gomes",
    testimony: "Equipe muito profissional e dedicada.",
  },
  {
    id: 9,
    href: "https://maps.app.goo.gl/fakeLink9",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    name: "Eduardo Martins",
    testimony: "Resolveram meu problema rapidamente.",
  },
  {
    id: 10,
    href: "https://maps.app.goo.gl/fakeLink10",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef",
    name: "Bruna Carvalho",
    testimony: "Ótimo suporte e comunicação.",
  },
] as const;
